version: "3.9"
services:

  redis:
    image: "redis:5.0.6"
    ports:
      - "6379:6379"

  app:
    build: .
    environment:
      REDIS_URL: redis://redis
    ports:
      - 8000:8000
    depends_on:
      - redis
